// Generates lib/tech.ts: every technology we work with, grouped, with its
// Simple Icons path (CC0) when the brand ships one. Run: node scripts/gen-tech.mjs
import * as si from "simple-icons";
import { writeFileSync } from "node:fs";

const groups = {
  frontend: ["HTML5", "CSS", "JavaScript", "TypeScript", "React", "Next.js", "Vue.js", "Nuxt", "Angular", "Svelte", "Astro", "Tailwind CSS", "Sass", "Vite", "Webpack", "Redux", "GSAP", "Three.js", "Storybook"],
  backend: ["Node.js", "Express", "NestJS", "Bun", "Deno", "Python", "Django", "FastAPI", "Flask", "PHP", "Laravel", "Go", "Rust", "Java", "Spring Boot", ".NET", "C#", "Ruby on Rails", "GraphQL", "tRPC", "Prisma", "Socket.io", "Zod"],
  mobile: ["Swift", "SwiftUI", "Kotlin", "Jetpack Compose", "Android", "iOS", "Flutter", "Dart", ["React Native", "React"], "Expo", "Firebase", "Xcode", "Android Studio", "Electron", "Tauri"],
  data: ["PostgreSQL", "MySQL", "MongoDB", "Redis", "Elasticsearch", "ClickHouse", "SQLite", "Supabase", "RabbitMQ", "Apache Kafka", "Meilisearch", "MinIO"],
  devops: ["Docker", "Kubernetes", "NGINX", "Linux", "Ubuntu", "Debian", "Git", "GitHub", "GitLab", "GitHub Actions", "Jenkins", "Terraform", "Ansible", "Prometheus", "Grafana", "Sentry", "Vault", "Keycloak"],
  cloud: ["Amazon Web Services", "Google Cloud", "Microsoft Azure", "Cloudflare", "Vercel", "Netlify", "DigitalOcean", "Hetzner", "Yandex Cloud"],
  ai: ["OpenAI", "Anthropic", "Claude", "Google Gemini", "LangChain", "Hugging Face", "PyTorch", "TensorFlow", "Ollama", "n8n", "Make", "Zapier"],
  integrations: ["Telegram", "WhatsApp", "Stripe", "PayPal", "Payme", "Click", "1C", "Bitrix24", "amoCRM", "Google Maps", "Mapbox", "Twilio", "Auth0", "Clerk"],
  cms: ["WordPress", "Shopify", "Strapi", "Sanity", "Contentful"],
  design: ["Figma", "Framer", "Adobe Illustrator", "Adobe Photoshop"],
  analytics: ["Google Analytics", "Google Tag Manager", "Google Ads", "Meta", "Yandex Metrica"],
  tools: ["Jest", "Vitest", "Cypress", "Playwright", "Postman", "Swagger", "Jira", "Notion", "Trello", "Slack", "Visual Studio Code", "npm", "pnpm"],
};

const byTitle = new Map(Object.values(si).map((i) => [i.title.toLowerCase(), i]));
const out = {};
for (const [group, names] of Object.entries(groups)) {
  out[group] = names.map((entry) => {
    const [name, iconTitle] = Array.isArray(entry) ? entry : [entry, entry];
    const icon = byTitle.get(iconTitle.toLowerCase());
    return icon ? { name, hex: `#${icon.hex}`, path: icon.path } : { name };
  });
}

const body = `/* Generated by scripts/gen-tech.mjs — do not edit by hand.
 * Logos: Simple Icons (CC0). Brands without an icon render as a wordmark. */
export type Tech = { name: string; hex?: string; path?: string };
export const techGroups = ${JSON.stringify(out, null, 2)} as const satisfies Record<string, readonly Tech[]>;
export type TechGroup = keyof typeof techGroups;
`;
writeFileSync("lib/tech.ts", body);
console.log(Object.values(out).flat().length, "technologies");
